version: '3.7'

services:
    database:
        image: dio-db
        restart: always
        ports:
            - "3306:3306"
        environment:
            -  MYSQL_ROOT_PASSWORD=rootpasswd
            -  MYSQL_DATABASE=dio_me
            -  MYSQL_USER=user
            -  MYSQL_PASSWORD=userpasswd
        volumes:
            - "data:/var/lib/mysql"   
    phpmyadmin:
        image: phpmyadmin
        restart: always
        links:
            - database
        ports:
            - "80:80" 
        environment:
            - PMA_HOST=database
            - PMA_PORT=3306  
volumes:
    data:        
